### ISSUE TITLE
Missing dependencies in vendor/

### ISSUE THREAD

**Issue by mossroy** [stefan-muc/caldav-calendar-import#2]
Many thanks for this script.

To make it work, after running `composer install`, I had to manually install a few php files in vendor folder : 

- caldav-client-v2.php (I took it from https://gitlab.com/davical-project/davical/blob/master/inc/caldav-client-v2.php)
- AWLUtilities.php, Translation.php, XMLDocument.php, and XMLElement.php (I took these 4 files from https://github.com/wvrzel/simpleCalDAV/tree/master/include)

Did I miss an installation step? Or should these dependencies be automatically installed by composer?

In any case, it now works well, thanks!

**Comment by stefan-muc** [comment]
You're welcome mossroy!

Thanks for pointing out these shortcomings. No you did all right, I missed to add these files most probably because I added ``vendor`` to ``.gitignore``. 
You indeed found the correct files (I personally used AWL version 0.53, but it seems better to stick to 0.54 you found).

I moved these files to ``include``, added them to the repository and released a new version 0.1.2

**Comment by mossroy** [comment]
I tested with version 0.3 and had no issue with dependencies.
This 0.3 version is also much improved as it separates code and configuration (with the config directory), and is much faster as it only modifies/adds/deletes what is necessary (instead of deleting/re-creating all events like in version 0.1)
Thanks a lot!

**Comment by stefan-muc** [comment]
Thank you very much! Yeah I had some time to do this. Great to hear that you like it!
